- name: Install launcher as service
  become: yes
  become_user: root
  template: src=launcher.conf.j2 dest=/etc/init/pvw-launcher.conf mode=644 owner=root
  notify:
    - restart launcher
  tags:
    - launcher

